<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <?php
        echo "hello";
        echo '<br>';
        echo "pranali";
        echo '<br>';
        echo '<br>';
        echo '<button>Click me</button>';
        
    ?>

    <?php
    
    $name ='pranali\'s has two cars';
    $age = 24;
    $nature = 'dangerous';
    $height = 5.4;
    $salar = null;
    $ismale= true;

    echo '<br>';
    echo '<br>';
    echo $name.'<br>';
    echo $age.'<br>';
    echo $nature.'<br>';
    echo $height.'<br>';
    echo $salar.'<br>';
    echo $ismale.'<br>';


    ?>

</body>
</html>